import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Hero from "@/Components/Hero";
import Collection from "@/Components/Collection";
import FAQ from "@/Components/FAQ";
import Experience from "@/Components/Experience";
import Reviews from "@/Components/Reviews";
import Salon from "@/Components/Salon";
import Salon2 from "@/Components/Salon2";
import Advertise from "@/Components/Advertise";
import Inspiration from "@/Components/Inspiration";
import More from "@/Components/More";
import Socail from "@/Components/Socail";
import Result from "@/Components/Result";
import SecondReviews from "@/Components/SecondReviews";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beauty by Arham",
  description: "Generated by Beauty by Arham",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Header/>
        <Hero/>
        <Collection/>
        <FAQ/>
        <Experience/>
        <Reviews/>
        <Salon/>
        <Salon2/>
        <Advertise/>
        <Inspiration/>
        <More/>
        <Socail/>
        <Result/>
        <SecondReviews/>
        {children}</body>
    </html>
  );
}
